on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: poetry-release-please-example
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          pip install poetry
          poetry install
        if: ${{ steps.release.outputs.release_created }}
      - run: echo PUBLISH
        if: ${{ steps.release.outputs.release_created }}
